<%= Rails.env %>:
  adapter:  postgresql
  encoding: unicode
  host:     <%= Figaro.env.DB_HOST%>
  database: <%= Figaro.env.DATABASE%>
  user:     <%= Figaro.env.DB_USER%>
  password: <%= Figaro.env.DB_PASSWORD%>
  pool:     <%= Figaro.env.DB_POOL%>
  timeout:  5000
